apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: external-prd-20211121.k8s.h3poteto.dev
spec:
  api:
    dns: {}
  authentication:
    aws: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://h3poteto-k8s-clusters/external-prd-20211121.k8s.h3poteto.dev
  dnsZone: Z21DTFU4BHSZ51
  containerRuntime: containerd
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-ap-northeast-1a
      name: a
    - encryptedVolume: true
      instanceGroup: master-ap-northeast-1c
      name: c
    - encryptedVolume: true
      instanceGroup: master-ap-northeast-1d
      name: d
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-ap-northeast-1a
      name: a
    - encryptedVolume: true
      instanceGroup: master-ap-northeast-1c
      name: c
    - encryptedVolume: true
      instanceGroup: master-ap-northeast-1d
      name: d
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    maxPods: 20
  kubeAPIServer:
    defaultNotReadyTolerationSeconds: 600
    defaultUnreachableTolerationSeconds: 600
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.22.8
  masterPublicName: api.external-prd-20211121.k8s.h3poteto.dev
  networkCIDR: 10.0.0.0/16
  networkID: vpc-fb354b9c
  networking:
    amazonvpc: {}
  nonMasqueradeCIDR: 10.0.0.0/16
  serviceAccountIssuerDiscovery:
    discoveryStore: s3://irsa-aa6871c4-6978-f7d4-3400-ad8eb7a7f811
    enableAWSOIDCProvider: true
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  subnets:
  - cidr: 10.0.0.0/20
    id: subnet-fa7f7fb3
    name: ap-northeast-1a
    type: Public
    zone: ap-northeast-1a
  - cidr: 10.0.16.0/20
    id: subnet-70bbc92b
    name: ap-northeast-1c
    type: Public
    zone: ap-northeast-1c
  - cidr: 10.0.32.0/20
    id: subnet-f45541dc
    name: ap-northeast-1d
    type: Public
    zone: ap-northeast-1d
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: external-prd-20211121.k8s.h3poteto.dev
  name: master-ap-northeast-1a
spec:
  iam:
    profile: arn:aws:iam::564677439943:instance-profile/k8s-master-profile
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20211015
  instanceMetadata:
    httpPutResponseHopLimit: 3
    httpTokens: required
  machineType: t3.small
  maxPrice: "0.025"
  maxSize: 2
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - t3.small
    - t2.small
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: lowest-price
    spotInstancePools: 2
  nodeLabels:
    kops.k8s.io/instancegroup: master-ap-northeast-1a
  role: Master
  rootVolumeSize: 20
  rootVolumeType: gp2
  securityGroupOverride: sg-0110c581f1db6223d
  subnets:
  - ap-northeast-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: external-prd-20211121.k8s.h3poteto.dev
  name: master-ap-northeast-1c
spec:
  iam:
    profile: arn:aws:iam::564677439943:instance-profile/k8s-master-profile
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20211015
  instanceMetadata:
    httpPutResponseHopLimit: 3
    httpTokens: required
  machineType: t3.small
  maxPrice: "0.025"
  maxSize: 2
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - t3.small
    - t2.small
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: lowest-price
    spotInstancePools: 2
  nodeLabels:
    kops.k8s.io/instancegroup: master-ap-northeast-1c
  role: Master
  rootVolumeSize: 20
  rootVolumeType: gp2
  securityGroupOverride: sg-0110c581f1db6223d
  subnets:
  - ap-northeast-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: external-prd-20211121.k8s.h3poteto.dev
  name: master-ap-northeast-1d
spec:
  iam:
    profile: arn:aws:iam::564677439943:instance-profile/k8s-master-profile
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20211015
  instanceMetadata:
    httpPutResponseHopLimit: 3
    httpTokens: required
  machineType: t3.small
  maxPrice: "0.025"
  maxSize: 2
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - t3.small
    - t2.small
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: lowest-price
    spotInstancePools: 2
  nodeLabels:
    kops.k8s.io/instancegroup: master-ap-northeast-1d
  role: Master
  rootVolumeSize: 20
  rootVolumeType: gp2
  securityGroupOverride: sg-0110c581f1db6223d
  subnets:
  - ap-northeast-1d

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: external-prd-20211121.k8s.h3poteto.dev
  name: nodes-ap-northeast-1a
spec:
  iam:
    profile: arn:aws:iam::564677439943:instance-profile/k8s-node-profile
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20211015
  instanceMetadata:
    httpPutResponseHopLimit: 3
    httpTokens: required
  machineType: t3.medium
  maxPrice: "0.05"
  maxSize: 2
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - t3.medium
    - t2.medium
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: lowest-price
    spotInstancePools: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-ap-northeast-1a
  role: Node
  rootVolumeSize: 20
  rootVolumeType: gp2
  securityGroupOverride: sg-02c91c8f054c85937
  subnets:
  - ap-northeast-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: external-prd-20211121.k8s.h3poteto.dev
  name: nodes-ap-northeast-1c
spec:
  iam:
    profile: arn:aws:iam::564677439943:instance-profile/k8s-node-profile
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20211015
  instanceMetadata:
    httpPutResponseHopLimit: 3
    httpTokens: required
  machineType: t3.medium
  maxPrice: "0.05"
  maxSize: 2
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - t3.medium
    - t2.medium
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: lowest-price
    spotInstancePools: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-ap-northeast-1c
  role: Node
  rootVolumeSize: 20
  rootVolumeType: gp2
  securityGroupOverride: sg-02c91c8f054c85937
  subnets:
  - ap-northeast-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: external-prd-20211121.k8s.h3poteto.dev
  name: nodes-ap-northeast-1d
spec:
  iam:
    profile: arn:aws:iam::564677439943:instance-profile/k8s-node-profile
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20211015
  instanceMetadata:
    httpPutResponseHopLimit: 3
    httpTokens: required
  machineType: t3.medium
  maxPrice: "0.05"
  maxSize: 2
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - t3.medium
    - t2.medium
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: lowest-price
    spotInstancePools: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-ap-northeast-1d
  role: Node
  rootVolumeSize: 20
  rootVolumeType: gp2
  securityGroupOverride: sg-02c91c8f054c85937
  subnets:
  - ap-northeast-1d
