apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2020-03-28T15:37:11Z"
  generation: 8
  name: external-prd-20200329.k8s.h3poteto.dev
spec:
  api:
    dns: {}
  authentication:
    aws: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://h3poteto-k8s-clusters/external-prd-20200329.k8s.h3poteto.dev
  dnsZone: Z21DTFU4BHSZ51
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-ap-northeast-1a
      name: a
    - instanceGroup: master-ap-northeast-1c
      name: c
    - instanceGroup: master-ap-northeast-1d
      name: d
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-ap-northeast-1a
      name: a
    - instanceGroup: master-ap-northeast-1c
      name: c
    - instanceGroup: master-ap-northeast-1d
      name: d
    memoryRequest: 100Mi
    name: events
  fileAssets:
  - content: |-
      AQECAHhRyjfcAU0BFeAevHu12PEb8p++xXO5Ct1XvR/ARXpyaQAACYcwggmDBgkqhkiG9w0BBwagggl0MIIJcAIBADCCCWkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMiyTjDZw7Wp1Pl4wDAgEQgIIJOu7poOYgL2+QILCQ6JfgPqXStZOSl/3RxZOnD9ctd9t4IvQmbjSoY05R4+1J2Y4PM5XkHq0bWmgcM2SjdtftkSU23o2KUSf07hKa5rIp0xit9MYd7mW1H7T1cq18hzI3Kv8++pS6N3e4x9gSOZrAKROoG7uw1Ad2ijBnqVzvdlTXyGJCh4YYHb/bdc+K2BAYMsmbUPooD36QcwQvYqT1x5pqq4gwoxShPtD8a16VcXgqP4EAiMb3NGv6u/9k89BuAHOXr4iZQw2IRL1f3VBtAi4XFB3DN5IIEHvGKC6j4WMrZlvs9y0sLd7Sm0McmPeimSWYv2cnTN9YPZy8EDfjv+yj3LpMvYZQTwb/ayKb6+rIHPrADgzhToRNQFTFLgm39n//ckqC81Pkn+iAPXX52YdcIPQiuvZMNOTTjDu7FYbtrDjv0b7XWwthYdeotx2HxkKP7DqoKHj+gsEaIMiPCkuOjlN9x4uuDOzsX7g7524C+M6LfFdaQLMjSJSFEarwfI1T9BcBYSyiHY7R8BTb9mm661A6t7M81wYiA1G2I+SK+rELPy089YEsP32AadQd1HDGyTIHVaIbEXAxV3Zw1Da6WehwH4bxU3pRlSzxkKcvyswTCFTMhN33t9i2PkVJtjUwj6aC1ikvuuS9Ats98UyGKV+xcef1yrtTKJRO/Ony25PD2UPoyXBjxK1WpsctA1GWJKkRbJQ04aGxsCYcElPXyZcAkXImONqXceybpOm6NodIv8CTw0A3P8NiVPrJNwZfua3Xp97J4zARO1sFsVJ57BF8WyYmP3PWDhYSzapOgMLsurvR6YO9J7gz5+H10s3UhXSJ+z9egYvHUXHrXJ+bGDZ8osNEykIiyhqYr5oUZPUHXTO+o+AYimSimpYfVsv92fb8V4tpx2Nee0cAf5Ht6viJYQsxj7spg61sAfolViedigK5oryCYeriD8GNTpl1s5vTigga8kWU4Rs+6HR+XCoqydKdgaTWl1jaOLEIDcZma8p84j9UoLGY1XZielwwN0OUWOA0MTnmYyK5Z7/XW8k8m7eoVO4Upyam6z1ZbMPRo9ka/44/F9/u+UJ4daEDMijt4xZFfyfsJpMFWjMDBvDFQ3EHgwXYzu4I43Z9AZIdYS0OTfgmk/B4sc6RmP3Y2W3JHNM6OwwM1a41y4e0vx+I5aWUkJz5Q9Nr0EtbyeNPaPMEmH+IkXg9NVFjM63VVVO7j/c8bXPDRB46WYZSN5N6fSpG8DnHW0SudSTWn9b5NQJXerQNTiu1yQI698IsRnUWASG1xEJmq5Ct29mXFRP0zEBPh8ibRX0skzXOdb6q1/MylPglPfBnmguDtQRN02T3muM+IzKBfJREpWQ8lEFVcax/5Aoi3BfS5kO7Cwcg1vzNVNgVz03cQoNE2YEUXpSZqbDG1v91Xz2RBiNcSlx4wuHt56MDBKMsLeP7hW+MeXvOFokefVr7+mI7AytgQP7TSzM0CuFMJyMXa/kw/1JHalePDMYnNp3bqymUtjWfl0bGrgwSiWSSyphguBtKtBj9m5aIt2CGtHqgnnAeHW/3dBROxa3ft2qyUt8s+vwdO8REsolUJtASv0lbJK5gOLSiSc/5J8WbVGHfCV0chxvre6bVdwP2VYnJov1qbG/ul0rGrTwZW7OAfkANyhPgBe0ooU54V4W8wWSjUL6dPpe4GigxR/cXkhf5ny+NFcVWH0aPqEte2JOwTDgSR6m+J1PSBMg3qiEEKeIl7g0fBSyjXbWsLgHFflSZ5qMsNQbX0A1uDCsy8esQfGsF6oj0FrYiiDCXl6zDtAUR4o1zX7yAiPuJAwcN/EmI+b6AqNxiEj5tQGppp5afbQCIwPFnMyoBzk2d5FYi/BGmRmjySblKxj561hIk4zFXx6l87yLS5sPsS92mwaa/ObYvxozrdefWe+8hmDVTidAIZTl8H5PxCXnaR7bHDvdIC8o+ICXdVR6q7KCqHwlNsNA1168NH1gznJ8T7QnrRyaafaYLUz2NHXmke98jlqxXhHFuewdDzgouFZZkKMTmuaAnBZjXkUJ2h2YGX+bgU2xZz4yquhMtCcHtv5EY2ckkEUmEYB4aylEU7IU6aeGCVJWHBdiX6WNvAD+N3QjQB53f9KqFvH6TQO8CCvC9PZryM/QtTVTq9aFYERmILvWnjg0pdUIhwCpf/EX4+H+EjbN54j7lnt9cCIV0rDaL7bUbBK4Z/7r6dFRxnyAcP81pKSA+4fHgl54uw5+ayEQIAvO6UK2wi/tLGgswX2QoiPnKecMNClAp/kxqA9rIXURa+JXjTSl3m5qM9zlVykZBae/US/gWbCp1Z3ZHXT0yaJ+jFIteR36eBwi3X24n6ptbeC9wGLJJ+2F99XYFIJmKFv6dEh2ojakJjDrIxL1JlDarKbkvqum0qBIhtJmNAzrJXVqiRSSIpamqmf628s0f5TnrF8GNU6dnHZCjCTosLSu5irgeAkJ0BFyVMejGO/XGIENI1yZe4gLn1bRnr4xBDjQVN5LF1MtqI/lwv+pYA5cxfWPzUju1abam+bo9dsdt5jeIicMRTxj4XPFTXK7hWfmOty3HCBqZ4b60sE6sJ5g/lygwbzZgty6dyvXnBWdAsrKsQBf/NKG5qHGqbaWJh2T0GD1BiL+ijYq90AOTJR7uM5ZI9yS17w5Dd3p9moLvS8EQCeVi6j2tt5/pMe96MuLw4ejJ4bPlEIV2mnVWe+99+i/kLO7uQ0GbfE+VWxIXv9sTTW+iwYOGROk2YY9VCuDmWHlH3nSjZ0W9sbh0jboqnwWyXd6aSrSNBPnKqCtYgANwEG9Ci/hHjcL5U9PfvC1RC6Bm8naFfLRafRxdeZ57v6RBPWigd6ypHzbhbKI4SI7MqYrxMvz8wu7v2TQw4KnvKdCsdX7GIE9iPyocjky6bMTNuSe3Q5Lxs4XqrBCRaIOpcyu9hU3hoHkbXyTxMI3O6mwReixB0blma1MBfNIPf4MVPcxV7YP+bPi+MLjyQOtm+kANK7sHt/el5NtakchY0YJk9FgZsl/E0KhOxKP6uvFOXFj6QhWh54PEbOgZl0l7Ry1FmUJFVeYpvdqNRdHGY+9HXltiOble1hrSeFJMYNnsP+WF1+xXlaX12zMhKr2u7s4/N8yWpEFRbvk=
    isBase64: AQECAHhRyjfcAU0BFeAevHu12PEb8p++xXO5Ct1XvR/ARXpyaQAAAGkwZwYJKoZIhvcNAQcGoFowWAIBADBTBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDAELjlrp41g/NmgwDAIBEIAml0MgIr+2Wj5bPQxNlIWIjB7XXhdh9ArEJEtuM0VdgSWFNByk9Co=
    name: AQECAHhRyjfcAU0BFeAevHu12PEb8p++xXO5Ct1XvR/ARXpyaQAAAIQwgYEGCSqGSIb3DQEHBqB0MHICAQAwbQYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAx2yqnk+YSgE3Lj/1ECARCAQAhtyV+ROZkbT4lemlsFBs3oeebTMWzZlJIB1qpgDb9s6E9F359eiBiomTNpL9Y6gTXsdahbYL55yHo997z92/U=
    path: AQECAHhRyjfcAU0BFeAevHu12PEb8p++xXO5Ct1XvR/ARXpyaQAAAJswgZgGCSqGSIb3DQEHBqCBijCBhwIBADCBgQYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAzWGAqUjdvQtShk6dUCARCAVOa4lInNJIWmMjz2yU1CPIDr6li9yLWwqMdhpsXSHe35rbw2R3hOXjgo+FfRf4oD2ReYPXxOsQLp5eTXmE/canXbyigpcS4mjMvGyP5FYsEciPPJtw==
  - content: |-
      AQECAHhRyjfcAU0BFeAevHu12PEb8p++xXO5Ct1XvR/ARXpyaQAAAuAwggLcBgkqhkiG9w0BBwagggLNMIICyQIBADCCAsIGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBRSqAO6xYlCqE3rOAgEQgIICk09yUBuZk49dn3Rz1+dkybA/d5iJ6wL3ry/2oVyQe51QVsjivwfZjS7TqnpeJoJFMWdACvl+ISCTxyzttZNP0hcwnPzJwlvdiw1qkN0tTpv0Gjz2hgyCOgekHvY4Wfpy0jwW2A0c7DDeZ11vj89CrlWMz2OiV1HqTRo6iIzgtbBAK4SHx0CC0STL02Lw7Wu/BRpkWBgg5WnUxMxOCF1DgLx/ndwvA+7ZUR5ugry1MRcOm7zTGUu3A6O8XYcSC8aqGF3QYiQaYpvM8QUI3zuT8tro+ykYQHybjVdiJNddw1tZrCNxUAjrm2OPMf9Uiru1yL2wfrWgdNzxUgMO+Jr9E52GNq7qHypojj8a6G8W/R1ESI2t0UprifeQ7mpklY4mlsrgKlpKo2ASow69I5NEusrSPU3i6/4iyOih4s24EK1NZDF2d4q3BHl4amA4fiDZ9Ajh8ecd4ssJIRUFGrximuBTDLM2dr7e9Sm9qJ5hirA2G+NlQoYthBBgs2apxuvltuaR0LYQnrVdB9LhtASPLWUueQriL7+4f1/tYncNBHYsEgCLFYoS6KsKiwYXvmx0dXTZQhGAqGn6JRjz61j9F29swk4cSZRkWTxGc/laDp7cWwtyPgtmPpp3g78b0Ng2QpZwr2VunB8u/+z6JTD+ATOln4U5OGaMF6jk7l9Cwfiyaghr4IOinLkafyq5Zbkpn0gV/Ga0CBa6hFnFiFCGfg9Eykm0Nt9B6tLVCm9xnCGuUcy5Mb78g6rTs2DolEuN9Q7eyShDzql0t3TnGGMNXkIdghsXuYmSP/NEvFggx29i5Czjt2OUgL4/xSU+KIDTIYN/c7rR8flemnqzBG64WRRpENdUUgsTvHTlVdCD5UtmPKb7
    isBase64: AQECAHhRyjfcAU0BFeAevHu12PEb8p++xXO5Ct1XvR/ARXpyaQAAAGkwZwYJKoZIhvcNAQcGoFowWAIBADBTBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDELgWDXqaPhmjCibBQIBEIAmd/HhcERpMjPN1GXoftVb7xesZJqgVMqRb3r111VRVcrxjV/LChk=
    name: AQECAHhRyjfcAU0BFeAevHu12PEb8p++xXO5Ct1XvR/ARXpyaQAAAHsweQYJKoZIhvcNAQcGoGwwagIBADBlBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDC5Klj20Aq+HV7xo/gIBEIA4vVRa5Z61fwYS/z4A4avNT5r4CXjtGWEd1d7sarUDrGLBWNN9Vq8LBZz51AGYyiRaTuzfMow3X2I=
    path: AQECAHhRyjfcAU0BFeAevHu12PEb8p++xXO5Ct1XvR/ARXpyaQAAAJEwgY4GCSqGSIb3DQEHBqCBgDB+AgEAMHkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMWTYIv55DxIWFA72xAgEQgEwhoLGANKRHhPbQUfH+A56KLpAM1giNauI7AQlLX/CumMw4w4SUuPM3BK2UtSnXC2BYmXPybYRD7IfJ9TmTxdiUfV21PopUeUkmkbiC
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    apiAudiences:
    - AQECAHhRyjfcAU0BFeAevHu12PEb8p++xXO5Ct1XvR/ARXpyaQAAAKEwgZ4GCSqGSIb3DQEHBqCBkDCBjQIBADCBhwYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAzREwhD9G4kFctHJtsCARCAWhmqNFqgiRYnq/UYn+HYCMJHvT3YCQsJDnG3fXIyO/PX6E9RnJz7J/w7N1CP/Z2tgkOLePAvsMXkTKK3v+L+a48uOGD7/xpM6/6C6qo7L3MLZ8FKdGNRxLcTtg==
    serviceAccountIssuer: AQECAHhRyjfcAU0BFeAevHu12PEb8p++xXO5Ct1XvR/ARXpyaQAAAKkwgaYGCSqGSIb3DQEHBqCBmDCBlQIBADCBjwYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAyp7G1bo5qnTOPqaWICARCAYnveJp0Ehn2wh1YKvyQdmr77zyPFCV5acTNBHcR8mm9mE8/7EgYMo/Xc8AzgjYGxp/xOvy1Alr426zjtab+rXAZB1bLCZDx6XK+dkFoCfqNoz8dnTlMtpQxFLRLVN/xYUs0+
    serviceAccountKeyFile:
    - /srv/kubernetes/server.key
    - /srv/kubernetes/assets/service-account-key
    serviceAccountSigningKeyFile: /srv/kubernetes/assets/service-account-signing-key
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.17.9
  masterInternalName: api.internal.external-prd-20200329.k8s.h3poteto.dev
  masterPublicName: api.external-prd-20200329.k8s.h3poteto.dev
  networkCIDR: 10.0.0.0/16
  networkID: vpc-fb354b9c
  networking:
    amazonvpc: {}
  nonMasqueradeCIDR: 10.0.0.0/16
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.0.0.0/20
    id: subnet-fa7f7fb3
    name: ap-northeast-1a
    type: Public
    zone: ap-northeast-1a
  - cidr: 10.0.16.0/20
    id: subnet-70bbc92b
    name: ap-northeast-1c
    type: Public
    zone: ap-northeast-1c
  - cidr: 10.0.32.0/20
    id: subnet-f45541dc
    name: ap-northeast-1d
    type: Public
    zone: ap-northeast-1d
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
