apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-03-28T15:37:11Z"
  generation: 2
  labels:
    kops.k8s.io/cluster: external-prd-20200329.k8s.h3poteto.dev
  name: master-ap-northeast-1a
spec:
  iam:
    profile: arn:aws:iam::564677439943:instance-profile/k8s-master-profile
  image: kope.io/k8s-1.17-debian-stretch-amd64-hvm-ebs-2020-07-20
  machineType: t3.small
  maxPrice: "0.025"
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-ap-northeast-1a
  role: Master
  rootVolumeSize: 20
  rootVolumeType: gp2
  securityGroupOverride: sg-0110c581f1db6223d
  subnets:
  - ap-northeast-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-03-28T15:37:11Z"
  generation: 2
  labels:
    kops.k8s.io/cluster: external-prd-20200329.k8s.h3poteto.dev
  name: master-ap-northeast-1c
spec:
  iam:
    profile: arn:aws:iam::564677439943:instance-profile/k8s-master-profile
  image: kope.io/k8s-1.17-debian-stretch-amd64-hvm-ebs-2020-07-20
  machineType: t3.small
  maxPrice: "0.025"
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-ap-northeast-1c
  role: Master
  rootVolumeSize: 20
  rootVolumeType: gp2
  securityGroupOverride: sg-0110c581f1db6223d
  subnets:
  - ap-northeast-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-03-28T15:37:11Z"
  generation: 2
  labels:
    kops.k8s.io/cluster: external-prd-20200329.k8s.h3poteto.dev
  name: master-ap-northeast-1d
spec:
  iam:
    profile: arn:aws:iam::564677439943:instance-profile/k8s-master-profile
  image: kope.io/k8s-1.17-debian-stretch-amd64-hvm-ebs-2020-07-20
  machineType: t3.small
  maxPrice: "0.025"
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-ap-northeast-1d
  role: Master
  rootVolumeSize: 20
  rootVolumeType: gp2
  securityGroupOverride: sg-0110c581f1db6223d
  subnets:
  - ap-northeast-1d

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-03-28T15:37:11Z"
  generation: 4
  labels:
    kops.k8s.io/cluster: external-prd-20200329.k8s.h3poteto.dev
  name: nodes
spec:
  cloudLabels:
    datadog: enabled
  iam:
    profile: arn:aws:iam::564677439943:instance-profile/k8s-node-profile
  image: kope.io/k8s-1.17-debian-stretch-amd64-hvm-ebs-2020-07-20
  machineType: t3.medium
  maxPrice: "0.05"
  maxSize: 5
  minSize: 2
  nodeLabels:
    datadog: enabled
    kops.k8s.io/instancegroup: nodes
  role: Node
  rootVolumeSize: 20
  rootVolumeType: gp2
  securityGroupOverride: sg-02c91c8f054c85937
  subnets:
  - ap-northeast-1a
  - ap-northeast-1c
  - ap-northeast-1d
