apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: external-prd-20210225.k8s.h3poteto.dev
spec:
  api:
    dns: {}
  authentication:
    aws: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://h3poteto-k8s-clusters/external-prd-20210225.k8s.h3poteto.dev
  containerRuntime: containerd
  dnsZone: Z21DTFU4BHSZ51
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-ap-northeast-1a
      name: a
    - instanceGroup: master-ap-northeast-1c
      name: c
    - instanceGroup: master-ap-northeast-1d
      name: d
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-ap-northeast-1a
      name: a
    - instanceGroup: master-ap-northeast-1c
      name: c
    - instanceGroup: master-ap-northeast-1d
      name: d
    memoryRequest: 100Mi
    name: events
  fileAssets:
  - content: |-
      AQECAHhRyjfcAU0BFeAevHu12PEb8p++xXO5Ct1XvR/ARXpyaQAACYcwggmDBgkqhkiG9w0BBwagggl0MIIJcAIBADCCCWkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMiNINoigoVnuqI8zYAgEQgIIJOrLsvzkwN2MteULp98Vg/ho28E4qfbdJzkYzim4h+EM8k6eXf7XA5qRVs1ZUM95KG8jJgXjbFTK6Xnk3q1Q5aItqCWSYie6+sjUWJjIsXlSicUVOCLOQoH1x7s/Iu4ydgH29dx2wTTsBf2uL0bmuVr6e5XakK2pseDZ3p4Fujbv+P4Vkp/W9M/D74Nn1ozQfVpZIIxq26nGEkXuIL29iYN9P71NiQVv2ODaeDOOVGveTWg4zhMejdYFKx/UaZCMARBxLrZzZMhCbSxaYYntlL7rf929V02QAQNXAxdN4v9T/FSwXWWJBThADKkbn9vzQ6YBYvB4PEX5F/9iJI04M6gx8XQW7iT7EW3Xd+viEjOTN2kal63s34KDgJoV5DoLB91wAuhC7YatuzJjOrrMom9rm6BkRQaj3ThAm5O6deRFsGQJe/D1g1cfBHzn9kRI7z8CEz8VJ+TItJI5e3JrpowV5MpOSAPdSJouSyzOjWXO+iH60lzZBDj8XnC18JNEu+2062EZC5jlB04T4fDPzTfi78fo4K5z9UQBobZ/Z2VbkR2T8mOrlKzshcl8GI0jBCoi4lhFFHgwOKU1lS54RQOjDAmHmYnUjW7wrf328AtMy4UvvL2krbOskCDF5G5r4pAQ169L0Yz06ZtTmx9fs8KFVL5cT32X4+IBmvLLOPdMinKKFT69QlGb+iak8h8CE81y/Btz2NNxjB9srdcSXyF2EXY2dD3UG0A7D3Ng8tNW5GZ/0ypnvfrdtJd9PtP/GxYOgbwRjEZ6knL2ZbhVlB/MGPE4r1h2XKnbUKjlkFnAe3J9aQzyEciZbjZ4No5pjaWWM9E2JYa2tNmd1GC2E+O+oyUDb+42kS6cO7yLE3YAsbwx3xe+Ri53NFynYHN0Mq512ZNefa3Yq2BEyYoLH8pY30TgZSW9fZdc1Ga1mqJgR4T36v1kQb5SctFX0JbKTf0yB7ZQzT3DUX4dseKlW3Ht2bxBBMOiSISpiEfeYx9tFyeMjxW21eCBpqUOPqHFv9642O5oQYqQBQNt8red1iKqodea8jOuvzWBbSj+hELml7PJE+jJs0WAEdSzFWPFg2yXdP5Z0jyvn01NFG3JkN+9kKEDSgRFuOZWZtmAMCRcIxPmxP68TmDoj5bnJgPfdJacA/LG68bT7L+K225eMDVChT+vXutTINPyWNdweEEfqD5QhC+GzJ8H/ybzPZpcwxErAFuemGqEyw8GEajnUdizKuquLMCXI6d8apl06rYk0bH0SJ9zZ5MDiw3ovphr0GSrWvezW2Q0GKKGl4VF/h+yBmrwFDuAOBg/lJw1KcorE7FZTFgK3WYXp6upVxN7PJkaF8/RXZsYgnyyIYjD6PMJpbTUKnoB1Ci5eHiEkQUrkqKsowuVHQj4RWaXGTVJlHq9qBoziMZBgZuc75R6iUFI17ZZgD2OCT/g3tZCj8GyYSz1k24k3cXkzCrOsoLMFDy6derK6qC4dhtkRCDLsLHJXH2HysY6gLkggSWQLB2eRIzLzLg2rGDfivpJCvoqklW5vWszvcaV7i68aloOmubzYdZ6PTKsC2GDi4WEgX2f3Y2d1P6keYstVWo/rNy+VHpLYSC88RmeesFA7zlzefKvxSg5h4ok9z7CbWSuhNQ6nL23C4+VBGNoeia4C/mltGW6JV+LNIDVLn2PN9JMELQkThSBA8dWJ51qShqvA+vr1v6xYzhOec4FxLPllhrRQP6CR//L30Y2CxbFUXyiQdYm5zeF4glkd9wHdnPfxojEgmXQYl+B1OcCpsR9l073eqlXOl3SRPZd/EOOft/KB5oAz/79YjEgBWK9vsrjOXYuaspVgYuVuA8RduVagF5LbB+HRnM4iTf7KnG9/RWh6UG6Pa0F1dHQkrmkrFE0a+GMU/u5DngsIg2dh6z8f26qV9HCGxCw5QBaWlyYEAWc+c+5QIxRagUy4Cm+3oPmTbWPhez0dWKS9m9Fwb6SQQygOPA+VIkXDREfscJEwngpjZkWE5TRGfTSFWQ/5IrQ9DWX09FBuOZqRorHmkiSU6WQ3ACsxbBsA2VNGKQtHtPb18PnFC/mtCL1w+LAThdmj3yUfYsobdFwPmsk1jguPTGSx20Ty3rYfSTx5w4X/0TN0x5BrfI2wUgiz+o/+Uw7XV4Mx7ZXU8cLR52QDAORVjdt5812LwfmNCFVsNCQMUPex4S+h0WxBtmnlbN2Wf5SI+f4cYLxh02NCTyLHbAt6VRDytmWlysKLXR/PCIOPfAekXq2t6Z/vjUfEtHqfd6pIkDyTDFYPJejG1UPAIVHnCpZ7TKvG4VoYshUfbGsCUcIq42c/TEqriXtXyyLDzj+c6/LuAwCPa3KXUJW+Zhcw3FKqh8CSGgEx62z1eldRzDCAtbWRig4payOhk7g8DpBj1cGClafsTVA84J3XPW9LFh+vwnE+MXx6FqpqMGIpQ/L94iyNFb1ueHBnTuSvtDbt+nX8q1hKfH2q21OfU2RxeMt253XPIhKXw/F1Shpl+wwPMgk85ZY+DzQFKxYsL6pMWUeqVjSudJtg8F1ItPIu/lVB9jd1VmV/2pa2MBi78+rOuYWKqW7CgVaxuuVB6TikJkndaYkd43j0+wMV/nEj0cjmkSReMyci47Y0hKCM89+gWr2iASDt0hhJpoVuzaiq6S1j3Sw7sEIFd19rMdM4JPpUbtTmhzJSZ/jD97cabp4Nz5QMm1BGJslxM0fenf1bkzQWauTqWy3cYu8ahK485JwnBSw9fLKYIMLGziYLIIh9wcMxQUXLDSkccmOWxhIU+wfMffXBR3BKI+3fnaCjtRZIcZx/1elqd9KCASWFH075WB5qU7/7gCoBHTbItNyJqXhH+9ou5P4E+NJS0DXl/siAhQO8Vzaposg3okQlXkiW0QhyMbxDWR3rmuHF+3YqKM5HTKuq2XGluXBn0NR/6weJ/uzoQnIDtEsmkpf8PlgU0pva0J4KYlP++na2XVd0P4R02KVOX+dfjWKQd92zJrAiVT6mmGNdGr9qTb70awICSsEl72d14K849ta928HjVzgoEEPRcid2Sx27TG5q2Wdkngu2sFMZ3C2LkqS6SD6eO0g/CgNixdU7Tdlyd/rVkttBGBFyFEH81B2gtU8p26oSSt9m5g+Bm4/o1C8=
    isBase64: AQECAHhRyjfcAU0BFeAevHu12PEb8p++xXO5Ct1XvR/ARXpyaQAAAGkwZwYJKoZIhvcNAQcGoFowWAIBADBTBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDMsJziZlcRloc1mRZQIBEIAmjNA2TBBWBkPcERowLoVQS6piJCpcFa1H78Z/G7d9DvrV9necwMQ=
    name: AQECAHhRyjfcAU0BFeAevHu12PEb8p++xXO5Ct1XvR/ARXpyaQAAAIQwgYEGCSqGSIb3DQEHBqB0MHICAQAwbQYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAz2NSEYBSLjTSMKSfYCARCAQK2+qLJsZke6kNGgE7d/Rfd2m8EE5Zcd7R7xVLQWQlxp4bPPK2p8JetuG1L79aKJlJwEKnCZnxBgtxfSxHC9P8E=
    path: AQECAHhRyjfcAU0BFeAevHu12PEb8p++xXO5Ct1XvR/ARXpyaQAAAJswgZgGCSqGSIb3DQEHBqCBijCBhwIBADCBgQYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAyTgxMzmqJV1n/Jt/MCARCAVL5ObAZWZRX1tvKniFf1BMUrqoISYF0Tm170iVoqJtMen/yZrkouq19WQQYz5JwnKiQP3fZqNcGQBiPGKyMWVPiVUDnRrZo8+5Sd0cjKMm3X/P1GSA==
  - content: |-
      AQECAHhRyjfcAU0BFeAevHu12PEb8p++xXO5Ct1XvR/ARXpyaQAAAuAwggLcBgkqhkiG9w0BBwagggLNMIICyQIBADCCAsIGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMf2M0x7KtT2NPJSx6AgEQgIICk64mlDSsMKo5UdYCvJUFDvSRAqazucCWhfObuIN2QuoD67Chc2CszZALlTwBWt5syzWrhfOFjO0KDu+83Ebu8PJmwzgyRSMvdPR36W6wOdV78srJ+ZP84ERChjlUuUO+j5I2DVImIzBKxoykvRs2AgG9oepENaYjJPKJCCzV6aOiZQVgm/AQLaJM0woMzB9I6LPMbd2GBJqz//8b+SNUNjN48JP5gIgTMHBDw6n9AOL/coouVu22PJToBHS4N8Jk5Xo8d1TpGOqK8OMlR5jIBTNGDHn/cKO+TuIoi66/EwUSAnSJdPa7G4KD2J+Av+1X4dyHsBg3402npCC65hGozlZgw0juMfuucKhjUwDCFF5HphVAOGAe2Qvx4/STm6LRwJbBvRBuyyzEA8qYLPFTke9Wbb3WLgWNyzRDnD6hiDVz3FEdtkI1FLEyAnNKjjZ6pE4/dPEe0yPt/wV2spqxq32tqAJbqfQllRIGGP31JkfQPy2IvTgCxbeaLsXRdnpK+b62NSPNMiLYsaQGRTanqy4hRc9l0IhkNX5ffE0HJjA9w1DOsbHDLoH4OVQ7LCDHAn9iHwSRBHI/w1RSyALi2dnkxTiWNHRv6P6qTmlBtTKqYuiTmo/UPYDmbEZE/lpwG4d/vVkvXVi8m7XHR/kfgrz67Xklub2/dPeujgpnWNd2TZ6i0o9bp0EhtqyPfMUEsokN7vDxdBuimk7KCaqaRigcjDyO314N97wAToh9cH9Zha1m0WzUYzlwQ3IBbxhvuh5GTl8eFs2mEHyG2Cga4O3y5MDUaYgJeTP54rSwXnZhxHEhDDxfm+Rr9zfyAck2bF4BmZHhILamo2JA8LafeG/+nh/8cv5kmgjOnVen17vC+Zea
    isBase64: AQECAHhRyjfcAU0BFeAevHu12PEb8p++xXO5Ct1XvR/ARXpyaQAAAGkwZwYJKoZIhvcNAQcGoFowWAIBADBTBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDPcCEXgxJb3fn9k9MgIBEIAmU+MvlDa/Bly2vGTzHz/J3snGMB8IcWW4C4DN3LOtAcJYDX8wIpc=
    name: AQECAHhRyjfcAU0BFeAevHu12PEb8p++xXO5Ct1XvR/ARXpyaQAAAHsweQYJKoZIhvcNAQcGoGwwagIBADBlBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDMeWfsrYFZF11OvjBwIBEIA4fC5lQnC41t7wnvNYo59/aAi+zvxOV2R2vfAsQzQtKWI+49t2w6iPWRc645lOBTE5lKNgEFNHI4w=
    path: AQECAHhRyjfcAU0BFeAevHu12PEb8p++xXO5Ct1XvR/ARXpyaQAAAJEwgY4GCSqGSIb3DQEHBqCBgDB+AgEAMHkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMck0qGTh7cAT2mMsEAgEQgEwd/ZCAsZnihB7W7Q5Yy09y3dae8vFTXlM3uZn4di5nTYHe0S16DbOLBCqvAPueiMJ044UYtolAC5Kdyy9UH6zVrjYS4ncoQAkt2Scf
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    apiAudiences:
    - AQECAHhRyjfcAU0BFeAevHu12PEb8p++xXO5Ct1XvR/ARXpyaQAAAKEwgZ4GCSqGSIb3DQEHBqCBkDCBjQIBADCBhwYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAyInZ7WD9V7cB2W8SQCARCAWvZvjWWDUfQHC+Na1XPymgUslFstdmdZAj2GYsN2RHFmiaomVQ43ql/s00nY1v+9PcS62FHJd4Lcf7awh/h9ePa7PIjYdYa/xdO8e8o3gw9o9/49CbNxwfHzcg==
    serviceAccountIssuer: AQECAHhRyjfcAU0BFeAevHu12PEb8p++xXO5Ct1XvR/ARXpyaQAAAKkwgaYGCSqGSIb3DQEHBqCBmDCBlQIBADCBjwYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAyvSxOM5p93tBTnxu8CARCAYtQFtCbciaOPGatQtnVxP0nD6QQffwnQGbiuOhEnqcduJ3Q/YvKJB5cO0+ONUXNoHJPlHSyG2zYrE28q8ViSKAJ6Fhl3hWLugiK1rWcdu5KHeHprIhPDEQVshAl8WEkQ5Ojs
    serviceAccountKeyFile:
    - AQECAHhRyjfcAU0BFeAevHu12PEb8p++xXO5Ct1XvR/ARXpyaQAAAH8wfQYJKoZIhvcNAQcGoHAwbgIBADBpBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDLoJV5x+eyrKnfTXlgIBEIA8KI4Qost33LbhR2G/fqJMZ2vV0wtkI0Z3GyygJ/5rk+gEJojrFlWi3i4OiOCAprK0ilAn2iL0U+hQ5H7A
    - AQECAHhRyjfcAU0BFeAevHu12PEb8p++xXO5Ct1XvR/ARXpyaQAAAJEwgY4GCSqGSIb3DQEHBqCBgDB+AgEAMHkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMgIb26KjsO9S5Iua3AgEQgEz4gyAz02XoNFxkQg2v1AdMAA4a3o2wRxQK+bxYm9mlS5VhNc7T8Rfa0iv5K/gdj4etr202Rs2JBxdWzVYKm6wfnT/GONcIYWmUs0E5
    serviceAccountSigningKeyFile: AQECAHhRyjfcAU0BFeAevHu12PEb8p++xXO5Ct1XvR/ARXpyaQAAAJswgZgGCSqGSIb3DQEHBqCBijCBhwIBADCBgQYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAwwUEeQaJT9j5UyfU8CARCAVK3YWfeITM5Evt9fEZuzvFyPQuSPin40C3gr+XX5aw5xydJZXjMxIzE75rbUqM4EWi4g07zRwX+KBsk/8uwZaCHQYdx5/ApjW8iJ+T1NO9iBgs4XlQ==
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.21.4
  masterInternalName: api.internal.external-prd-20210225.k8s.h3poteto.dev
  masterPublicName: api.external-prd-20210225.k8s.h3poteto.dev
  networkCIDR: 10.0.0.0/16
  networkID: vpc-fb354b9c
  networking:
    amazonvpc: {}
  nonMasqueradeCIDR: 10.0.0.0/16
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.0.0.0/20
    id: subnet-fa7f7fb3
    name: ap-northeast-1a
    type: Public
    zone: ap-northeast-1a
  - cidr: 10.0.16.0/20
    id: subnet-70bbc92b
    name: ap-northeast-1c
    type: Public
    zone: ap-northeast-1c
  - cidr: 10.0.32.0/20
    id: subnet-f45541dc
    name: ap-northeast-1d
    type: Public
    zone: ap-northeast-1d
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: external-prd-20210225.k8s.h3poteto.dev
  name: master-ap-northeast-1a
spec:
  iam:
    profile: arn:aws:iam::564677439943:instance-profile/k8s-master-profile
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: t3.small
  maxPrice: "0.025"
  maxSize: 2
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - t3.small
    - t2.small
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: lowest-price
    spotInstancePools: 2
  nodeLabels:
    kops.k8s.io/instancegroup: master-ap-northeast-1a
  role: Master
  rootVolumeSize: 20
  rootVolumeType: gp2
  securityGroupOverride: sg-0110c581f1db6223d
  subnets:
  - ap-northeast-1a
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: external-prd-20210225.k8s.h3poteto.dev
  name: master-ap-northeast-1c
spec:
  iam:
    profile: arn:aws:iam::564677439943:instance-profile/k8s-master-profile
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: t3.small
  maxPrice: "0.025"
  maxSize: 2
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - t3.small
    - t2.small
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: lowest-price
    spotInstancePools: 2
  nodeLabels:
    kops.k8s.io/instancegroup: master-ap-northeast-1c
  role: Master
  rootVolumeSize: 20
  rootVolumeType: gp2
  securityGroupOverride: sg-0110c581f1db6223d
  subnets:
  - ap-northeast-1c
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: external-prd-20210225.k8s.h3poteto.dev
  name: master-ap-northeast-1d
spec:
  iam:
    profile: arn:aws:iam::564677439943:instance-profile/k8s-master-profile
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: t3.small
  maxPrice: "0.025"
  maxSize: 2
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - t3.small
    - t2.small
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: lowest-price
    spotInstancePools: 2
  nodeLabels:
    kops.k8s.io/instancegroup: master-ap-northeast-1d
  role: Master
  rootVolumeSize: 20
  rootVolumeType: gp2
  securityGroupOverride: sg-0110c581f1db6223d
  subnets:
  - ap-northeast-1d
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: external-prd-20210225.k8s.h3poteto.dev
  name: nodes-ap-northeast-1a
spec:
  iam:
    profile: arn:aws:iam::564677439943:instance-profile/k8s-node-profile
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: t3.medium
  maxPrice: "0.05"
  maxSize: 2
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - t3.medium
    - t2.medium
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: lowest-price
    spotInstancePools: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-ap-northeast-1a
  role: Node
  rootVolumeSize: 20
  rootVolumeType: gp2
  securityGroupOverride: sg-02c91c8f054c85937
  subnets:
  - ap-northeast-1a
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: external-prd-20210225.k8s.h3poteto.dev
  name: nodes-ap-northeast-1c
spec:
  iam:
    profile: arn:aws:iam::564677439943:instance-profile/k8s-node-profile
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: t3.medium
  maxPrice: "0.05"
  maxSize: 2
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - t3.medium
    - t2.medium
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: lowest-price
    spotInstancePools: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-ap-northeast-1c
  role: Node
  rootVolumeSize: 20
  rootVolumeType: gp2
  securityGroupOverride: sg-02c91c8f054c85937
  subnets:
  - ap-northeast-1c
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: external-prd-20210225.k8s.h3poteto.dev
  name: nodes-ap-northeast-1d
spec:
  iam:
    profile: arn:aws:iam::564677439943:instance-profile/k8s-node-profile
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: t3.medium
  maxPrice: "0.05"
  maxSize: 2
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - t3.medium
    - t2.medium
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: lowest-price
    spotInstancePools: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-ap-northeast-1d
  role: Node
  rootVolumeSize: 20
  rootVolumeType: gp2
  securityGroupOverride: sg-02c91c8f054c85937
  subnets:
  - ap-northeast-1d
