apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: playground.k8s.h3poteto.dev
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  authentication:
    aws: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://h3poteto-k8s-playground/playground.k8s.h3poteto.dev
  etcdClusters:
    - cpuRequest: 200m
      etcdMembers:
        - encryptedVolume: true
          instanceGroup: control-plane-ap-northeast-1a
          name: a
        - encryptedVolume: true
          instanceGroup: control-plane-ap-northeast-1c
          name: c
        - encryptedVolume: true
          instanceGroup: control-plane-ap-northeast-1d
          name: d
      manager:
        backupRetentionDays: 90
      memoryRequest: 100Mi
      name: main
    - cpuRequest: 100m
      etcdMembers:
        - encryptedVolume: true
          instanceGroup: control-plane-ap-northeast-1a
          name: a
        - encryptedVolume: true
          instanceGroup: control-plane-ap-northeast-1c
          name: c
        - encryptedVolume: true
          instanceGroup: control-plane-ap-northeast-1d
          name: d
      manager:
        backupRetentionDays: 90
      memoryRequest: 100Mi
      name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeProxy:
    enabled: false
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    maxPods: 50
  kubernetesApiAccess:
    - 0.0.0.0/0
    - ::/0
  kubernetesVersion: 1.33.4
  networkCIDR: 172.16.0.0/16
  networkID: vpc-00ea717e1640613ea
  networking:
    cilium:
      enableNodePort: true
  nodeTerminationHandler:
    enabled: false
  serviceAccountIssuerDiscovery:
    discoveryStore: s3://h3poteto-irsa-discovery-store
    enableAWSOIDCProvider: true
  podIdentityWebhook:
    enabled: true
  certManager:
    enabled: true
    managed: true
  awsLoadBalancerController:
    enabled: true
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
    - 0.0.0.0/0
    - ::/0
  subnets:
    - id: subnet-0619c5276e1edce32
      cidr: 172.16.0.0/20
      name: ap-northeast-1a
      type: Public
      zone: ap-northeast-1a
    - id: subnet-04acc221370b74258
      cidr: 172.16.16.0/20
      name: ap-northeast-1c
      type: Public
      zone: ap-northeast-1c
    - id: subnet-06d07ea961e7e0007
      cidr: 172.16.32.0/20
      name: ap-northeast-1d
      type: Public
      zone: ap-northeast-1d
  topology:
    dns:
      type: Public

---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: playground.k8s.h3poteto.dev
  name: control-plane-ap-northeast-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-20250610
  machineType: t3.small
  maxSize: 1
  minSize: 1
  role: Master
  maxPrice: "0.03"
  mixedInstancesPolicy:
    instances:
      - t3.small
      - t2.small
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: lowest-price
    spotInstancePools: 2
  subnets:
    - ap-northeast-1a

---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: playground.k8s.h3poteto.dev
  name: control-plane-ap-northeast-1c
spec:
  image: 099720109477/ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-20250610
  machineType: t3.small
  maxSize: 1
  minSize: 1
  role: Master
  maxPrice: "0.03"
  mixedInstancesPolicy:
    instances:
      - t3.small
      - t2.small
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: lowest-price
    spotInstancePools: 2
  subnets:
    - ap-northeast-1c

---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: playground.k8s.h3poteto.dev
  name: control-plane-ap-northeast-1d
spec:
  image: 099720109477/ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-20250610
  machineType: t3.small
  maxSize: 1
  minSize: 1
  role: Master
  maxPrice: "0.03"
  mixedInstancesPolicy:
    instances:
      - t3.small
      - t2.small
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: lowest-price
    spotInstancePools: 2
  subnets:
    - ap-northeast-1d

---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: playground.k8s.h3poteto.dev
  name: nodes-ap-northeast-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-20250610
  machineType: t3.small
  maxSize: 1
  minSize: 1
  role: Node
  maxPrice: "0.03"
  mixedInstancesPolicy:
    instances:
      - t3.small
      - t2.small
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: lowest-price
    spotInstancePools: 2
  subnets:
    - ap-northeast-1a

---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: playground.k8s.h3poteto.dev
  name: nodes-ap-northeast-1c
spec:
  image: 099720109477/ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-20250610
  machineType: t3.small
  maxSize: 1
  minSize: 1
  role: Node
  maxPrice: "0.03"
  mixedInstancesPolicy:
    instances:
      - t3.small
      - t2.small
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: lowest-price
    spotInstancePools: 2
  subnets:
    - ap-northeast-1c

---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: playground.k8s.h3poteto.dev
  name: nodes-ap-northeast-1d
spec:
  image: 099720109477/ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-20250610
  machineType: t3.small
  maxSize: 1
  minSize: 1
  role: Node
  maxPrice: "0.03"
  mixedInstancesPolicy:
    instances:
      - t3.small
      - t2.small
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: lowest-price
    spotInstancePools: 2
  subnets:
    - ap-northeast-1d
