---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cilium-operator-additional
rules:
# to set NetworkUnavailable false on startup and remove cilium taint
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/status
  verbs:
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    addon.kops.k8s.io/name: networking.cilium.io
  name: cilium-operator-additional
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cilium-operator-additional
subjects:
- kind: ServiceAccount
  name: cilium-operator
  namespace: kube-system
