apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2019-03-16T01:40:14Z
  name: base-prd.cluster.k8s.local
spec:
  api:
    loadBalancer:
      securityGroupOverride: sg-08585f22f2c36a263
      type: Public
  authentication:
    aws: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://k8s-cluster-base-prd/base-prd.cluster.k8s.local
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-ap-northeast-1a
      name: a
    - instanceGroup: master-ap-northeast-1c
      name: c
    - instanceGroup: master-ap-northeast-1d
      name: d
    name: main
  - etcdMembers:
    - instanceGroup: master-ap-northeast-1a
      name: a
    - instanceGroup: master-ap-northeast-1c
      name: c
    - instanceGroup: master-ap-northeast-1d
      name: d
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.11.7
  masterInternalName: api.internal.base-prd.cluster.k8s.local
  masterPublicName: api.base-prd.cluster.k8s.local
  networkCIDR: 10.0.0.0/16
  networkID: vpc-fb354b9c
  networking:
    amazonvpc: {}
  nonMasqueradeCIDR: 10.0.0.0/16
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.0.0.0/20
    id: subnet-fa7f7fb3
    name: ap-northeast-1a
    type: Public
    zone: ap-northeast-1a
  - cidr: 10.0.16.0/20
    id: subnet-70bbc92b
    name: ap-northeast-1c
    type: Public
    zone: ap-northeast-1c
  - cidr: 10.0.32.0/20
    id: subnet-f45541dc
    name: ap-northeast-1d
    type: Public
    zone: ap-northeast-1d
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
