apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: external-20250615.k8s.h3poteto.dev
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  authentication:
    aws: {}
  certManager:
    enabled: true
    managed: true
  channel: stable
  cloudProvider: aws
  configBase: s3://h3poteto-k8s-clusters/external-20250615.k8s.h3poteto.dev
  dnsZone: Z21DTFU4BHSZ51
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: control-plane-ap-northeast-1a
      name: a
    - encryptedVolume: true
      instanceGroup: control-plane-ap-northeast-1c
      name: c
    - encryptedVolume: true
      instanceGroup: control-plane-ap-northeast-1d
      name: d
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: control-plane-ap-northeast-1a
      name: a
    - encryptedVolume: true
      instanceGroup: control-plane-ap-northeast-1c
      name: c
    - encryptedVolume: true
      instanceGroup: control-plane-ap-northeast-1d
      name: d
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeProxy:
    enabled: true
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    maxPods: 50
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.31.8
  masterPublicName: api.external-20250615.k8s.h3poteto.dev
  networkCIDR: 10.0.0.0/16
  networkID: vpc-fb354b9c
  networking:
    amazonvpc: {}
  nodeTerminationHandler:
    enabled: false
  nonMasqueradeCIDR: 100.64.0.0/10
  podIdentityWebhook:
    enabled: true
  serviceAccountIssuerDiscovery:
    additionalAudiences:
    - sts.amazonaws.com
    discoveryStore: s3://oidc-bbad73ea-f004-069d-b9fc-19118bd1641d
    enableAWSOIDCProvider: true
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  subnets:
  - cidr: 10.0.0.0/20
    id: subnet-fa7f7fb3
    name: ap-northeast-1a
    type: Public
    zone: ap-northeast-1a
  - cidr: 10.0.16.0/20
    id: subnet-70bbc92b
    name: ap-northeast-1c
    type: Public
    zone: ap-northeast-1c
  - cidr: 10.0.32.0/20
    id: subnet-f45541dc
    name: ap-northeast-1d
    type: Public
    zone: ap-northeast-1d
  topology:
    dns:
      type: Public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: external-20250615.k8s.h3poteto.dev
  name: control-plane-ap-northeast-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20250516
  machineType: t3.small
  maxSize: 1
  minSize: 1
  maxPrice: "0.03"
  mixedInstancesPolicy:
    instances:
    - t3.small
    - t3.medium
    - t2.medium
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: price-capacity-optimized
  capacityRebalance: false
  role: Master
  rootVolumeSize: 10
  rootVolumeType: gp3
  subnets:
  - ap-northeast-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: external-20250615.k8s.h3poteto.dev
  name: control-plane-ap-northeast-1c
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20250516
  machineType: t3.small
  maxSize: 1
  minSize: 1
  maxPrice: "0.03"
  mixedInstancesPolicy:
    instances:
    - t3.small
    - t3.medium
    - t2.medium
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: price-capacity-optimized
  capacityRebalance: false
  role: Master
  rootVolumeSize: 10
  rootVolumeType: gp3
  subnets:
  - ap-northeast-1d

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: external-20250615.k8s.h3poteto.dev
  name: control-plane-ap-northeast-1d
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20250516
  machineType: t3.small
  maxSize: 1
  minSize: 1
  maxPrice: "0.03"
  mixedInstancesPolicy:
    instances:
    - t3.small
    - t3.medium
    - t2.medium
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: price-capacity-optimized
  capacityRebalance: false
  role: Master
  rootVolumeSize: 10
  rootVolumeType: gp3
  subnets:
  - ap-northeast-1d

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: external-20250615.k8s.h3poteto.dev
  name: nodes-ap-northeast-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20250516
  machineType: t3.medium
  maxPrice: "0.05"
  maxSize: 2
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - t3.medium
    - t2.medium
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: price-capacity-optimized
  role: Node
  rootVolumeSize: 20
  rootVolumeType: gp3
  subnets:
  - ap-northeast-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: external-20250615.k8s.h3poteto.dev
  name: nodes-ap-northeast-1c
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20250516
  machineType: t3.medium
  maxPrice: "0.05"
  maxSize: 2
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - t3.medium
    - t2.medium
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: price-capacity-optimized
  role: Node
  rootVolumeSize: 20
  rootVolumeType: gp3
  subnets:
  - ap-northeast-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: external-20250615.k8s.h3poteto.dev
  name: nodes-ap-northeast-1d
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20250516
  machineType: t3.medium
  maxPrice: "0.05"
  maxSize: 2
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - t3.medium
    - t2.medium
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: price-capacity-optimized
  role: Node
  rootVolumeSize: 20
  rootVolumeType: gp3
  subnets:
  - ap-northeast-1d

---
apiVersion: kops.k8s.io/v1alpha2
kind: SSHCredential
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: external-20250615.k8s.h3poteto.dev
  name: admin
spec:
  publicKey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP/3jS1oMtOQo3mXtqA/y1dHhUtsuvpFA6oAQ0qEyP6b akira@kinugawa
